#!/bin/bash

# Ask for the project name
echo "Enter the name of your Python project:"
read PROJECT_NAME

# Create the main project folder
mkdir "$PROJECT_NAME"
cd "$PROJECT_NAME" || exit 1

# Create folders
mkdir src tests notebooks data

# Create starter files
touch src/__init__.py
echo "# $PROJECT_NAME

This is a Python project scaffold generated by an automated script.
" > README.md

echo "*.pyc
__pycache__/
.env
.DS_Store
.ipynb_checkpoints/
" > .gitignore

touch requirements.txt

# Success message
echo "Standard Python project layout created in $PWD"
